version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'deploying master branch'
            - run: ssh -v -o "StrictHostKeyChecking no" root@devero.dev "cd ~/projects/deverobot; git pull --rebase; ./publish.sh"
            - run: git push --follow-tags origin $(git branch)

workflows:
  version: 2.1
  workflow-name:
    jobs: 
      - build:
          filters:
            branches:
              only: master
