version: 2
orbs:
  node: circleci/node@3.0.0

jobs:
  executor:
    run_tests:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npx semantic-releaser
    
    build_release:
      - docker:
          -image: node:latest
        steps:
        - run: echo 'deploying master branch'
        - run: ssh -v -o "StrictHostKeyChecking no" root@devero.dev "cd ~/projects/deverobot; git pull --rebase; ./publish.sh"

workflows:
  version: 2
  watch_master:
    jobs: 
      - build:
          filters:
            branches:
              only: master
  test_and_release:
      jobs:
        - run_tests
        - build_release
        - release:
            requires:
               - run_tests
               - build_release
